# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: labyrinth.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'labyrinth.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0flabyrinth.proto\x12\tlabyrinth\"\x15\n\x13GetLabyrinthRequest\"9\n\x18GetLabyrinthInfoResponse\x12\r\n\x05width\x18\x01 \x01(\x05\x12\x0e\n\x06height\x18\x02 \x01(\x05\"\x18\n\x16GetPlayerStatusRequest\"d\n\x17GetPlayerStatusResponse\x12\r\n\x05score\x18\x01 \x01(\x05\x12\x0e\n\x06health\x18\x02 \x01(\x05\x12\x10\n\x08position\x18\x03 \x01(\t\x12\x18\n\x10remaining_spells\x18\x04 \x01(\x05\"(\n\x13RegisterMoveRequest\x12\x11\n\tdirection\x18\x01 \x01(\t\"&\n\x14RegisterMoveResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\"<\n\x0eRevelioRequest\x12\x17\n\x0ftarget_position\x18\x01 \x01(\t\x12\x11\n\ttile_type\x18\x02 \x01(\t\"+\n\x0fRevelioResponse\x12\x18\n\x10target_positions\x18\x01 \x01(\t\"+\n\x0f\x42ombardaRequest\x12\x18\n\x10target_positions\x18\x01 \x01(\t\"\"\n\x10\x42ombardaResponse\x12\x0e\n\x06result\x18\x01 \x01(\t2\x9a\x03\n\tLabyrinth\x12W\n\x10GetLabyrinthInfo\x12\x1e.labyrinth.GetLabyrinthRequest\x1a#.labyrinth.GetLabyrinthInfoResponse\x12X\n\x0fGetPlayerStatus\x12!.labyrinth.GetPlayerStatusRequest\x1a\".labyrinth.GetPlayerStatusResponse\x12O\n\x0cRegisterMove\x12\x1e.labyrinth.RegisterMoveRequest\x1a\x1f.labyrinth.RegisterMoveResponse\x12\x42\n\x07Revelio\x12\x19.labyrinth.RevelioRequest\x1a\x1a.labyrinth.RevelioResponse0\x01\x12\x45\n\x08\x42ombarda\x12\x1a.labyrinth.BombardaRequest\x1a\x1b.labyrinth.BombardaResponse(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'labyrinth_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETLABYRINTHREQUEST']._serialized_start=30
  _globals['_GETLABYRINTHREQUEST']._serialized_end=51
  _globals['_GETLABYRINTHINFORESPONSE']._serialized_start=53
  _globals['_GETLABYRINTHINFORESPONSE']._serialized_end=110
  _globals['_GETPLAYERSTATUSREQUEST']._serialized_start=112
  _globals['_GETPLAYERSTATUSREQUEST']._serialized_end=136
  _globals['_GETPLAYERSTATUSRESPONSE']._serialized_start=138
  _globals['_GETPLAYERSTATUSRESPONSE']._serialized_end=238
  _globals['_REGISTERMOVEREQUEST']._serialized_start=240
  _globals['_REGISTERMOVEREQUEST']._serialized_end=280
  _globals['_REGISTERMOVERESPONSE']._serialized_start=282
  _globals['_REGISTERMOVERESPONSE']._serialized_end=320
  _globals['_REVELIOREQUEST']._serialized_start=322
  _globals['_REVELIOREQUEST']._serialized_end=382
  _globals['_REVELIORESPONSE']._serialized_start=384
  _globals['_REVELIORESPONSE']._serialized_end=427
  _globals['_BOMBARDAREQUEST']._serialized_start=429
  _globals['_BOMBARDAREQUEST']._serialized_end=472
  _globals['_BOMBARDARESPONSE']._serialized_start=474
  _globals['_BOMBARDARESPONSE']._serialized_end=508
  _globals['_LABYRINTH']._serialized_start=511
  _globals['_LABYRINTH']._serialized_end=921
# @@protoc_insertion_point(module_scope)
