# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: driver.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'driver.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x64river.proto\x12\x06\x64river\"8\n\x12\x41mAvailableRequest\x12\x11\n\tdriver_id\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\"v\n\x13\x41mAvailableResponse\x12\x0f\n\x07ride_id\x18\x01 \x01(\t\x12\x10\n\x08rider_id\x18\x02 \x01(\t\x12\x17\n\x0fpickup_location\x18\x03 \x01(\t\x12\x13\n\x0b\x64\x65stination\x18\x04 \x01(\t\x12\x0e\n\x06status\x18\x05 \x01(\x05\"7\n\x11\x41\x63\x63\x65ptRideRequest\x12\x11\n\tdriver_id\x18\x01 \x01(\t\x12\x0f\n\x07ride_id\x18\x02 \x01(\t\"5\n\x12\x41\x63\x63\x65ptRideResponse\x12\x0f\n\x07ride_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\x05\"7\n\x11RejectRideRequest\x12\x11\n\tdriver_id\x18\x01 \x01(\t\x12\x0f\n\x07ride_id\x18\x02 \x01(\t\"5\n\x12RejectRideResponse\x12\x0f\n\x07ride_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\x05\"9\n\x13TimedOutRideRequest\x12\x11\n\tdriver_id\x18\x01 \x01(\t\x12\x0f\n\x07ride_id\x18\x02 \x01(\t\"7\n\x14TimedOutRideResponse\x12\x0f\n\x07ride_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\x05\";\n\x15RideCompletionRequest\x12\x11\n\tdriver_id\x18\x01 \x01(\t\x12\x0f\n\x07ride_id\x18\x02 \x01(\t\"9\n\x16RideCompletionResponse\x12\x0f\n\x07ride_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\x05\x32\xf4\x02\n\x06\x44river\x12\x46\n\x0b\x41mAvailable\x12\x1a.driver.AmAvailableRequest\x1a\x1b.driver.AmAvailableResponse\x12\x43\n\nAcceptRide\x12\x19.driver.AcceptRideRequest\x1a\x1a.driver.AcceptRideResponse\x12\x43\n\nRejectRide\x12\x19.driver.RejectRideRequest\x1a\x1a.driver.RejectRideResponse\x12I\n\x0cTimedOutRide\x12\x1b.driver.TimedOutRideRequest\x1a\x1c.driver.TimedOutRideResponse\x12M\n\x0c\x43ompleteRide\x12\x1d.driver.RideCompletionRequest\x1a\x1e.driver.RideCompletionResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'driver_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AMAVAILABLEREQUEST']._serialized_start=24
  _globals['_AMAVAILABLEREQUEST']._serialized_end=80
  _globals['_AMAVAILABLERESPONSE']._serialized_start=82
  _globals['_AMAVAILABLERESPONSE']._serialized_end=200
  _globals['_ACCEPTRIDEREQUEST']._serialized_start=202
  _globals['_ACCEPTRIDEREQUEST']._serialized_end=257
  _globals['_ACCEPTRIDERESPONSE']._serialized_start=259
  _globals['_ACCEPTRIDERESPONSE']._serialized_end=312
  _globals['_REJECTRIDEREQUEST']._serialized_start=314
  _globals['_REJECTRIDEREQUEST']._serialized_end=369
  _globals['_REJECTRIDERESPONSE']._serialized_start=371
  _globals['_REJECTRIDERESPONSE']._serialized_end=424
  _globals['_TIMEDOUTRIDEREQUEST']._serialized_start=426
  _globals['_TIMEDOUTRIDEREQUEST']._serialized_end=483
  _globals['_TIMEDOUTRIDERESPONSE']._serialized_start=485
  _globals['_TIMEDOUTRIDERESPONSE']._serialized_end=540
  _globals['_RIDECOMPLETIONREQUEST']._serialized_start=542
  _globals['_RIDECOMPLETIONREQUEST']._serialized_end=601
  _globals['_RIDECOMPLETIONRESPONSE']._serialized_start=603
  _globals['_RIDECOMPLETIONRESPONSE']._serialized_end=660
  _globals['_DRIVER']._serialized_start=663
  _globals['_DRIVER']._serialized_end=1035
# @@protoc_insertion_point(module_scope)
