# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import driver_pb2 as driver__pb2

GRPC_GENERATED_VERSION = '1.66.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in driver_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DriverStub(object):
    """Drivers announce to a server (chosen acc to load balancing) that they are available
    for a ride, and wait for a response. If the server has an offer, the client waits
    till the timeout for the user to accept/reject and responds accordingly
    Once the ride is completed, it announces that to a server too.

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AmAvailable = channel.unary_unary(
                '/driver.Driver/AmAvailable',
                request_serializer=driver__pb2.AmAvailableRequest.SerializeToString,
                response_deserializer=driver__pb2.AmAvailableResponse.FromString,
                _registered_method=True)
        self.AcceptRide = channel.unary_unary(
                '/driver.Driver/AcceptRide',
                request_serializer=driver__pb2.AcceptRideRequest.SerializeToString,
                response_deserializer=driver__pb2.AcceptRideResponse.FromString,
                _registered_method=True)
        self.RejectRide = channel.unary_unary(
                '/driver.Driver/RejectRide',
                request_serializer=driver__pb2.RejectRideRequest.SerializeToString,
                response_deserializer=driver__pb2.RejectRideResponse.FromString,
                _registered_method=True)
        self.TimedOutRide = channel.unary_unary(
                '/driver.Driver/TimedOutRide',
                request_serializer=driver__pb2.TimedOutRideRequest.SerializeToString,
                response_deserializer=driver__pb2.TimedOutRideResponse.FromString,
                _registered_method=True)
        self.CompleteRide = channel.unary_unary(
                '/driver.Driver/CompleteRide',
                request_serializer=driver__pb2.RideCompletionRequest.SerializeToString,
                response_deserializer=driver__pb2.RideCompletionResponse.FromString,
                _registered_method=True)


class DriverServicer(object):
    """Drivers announce to a server (chosen acc to load balancing) that they are available
    for a ride, and wait for a response. If the server has an offer, the client waits
    till the timeout for the user to accept/reject and responds accordingly
    Once the ride is completed, it announces that to a server too.

    """

    def AmAvailable(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AcceptRide(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RejectRide(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TimedOutRide(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CompleteRide(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DriverServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AmAvailable': grpc.unary_unary_rpc_method_handler(
                    servicer.AmAvailable,
                    request_deserializer=driver__pb2.AmAvailableRequest.FromString,
                    response_serializer=driver__pb2.AmAvailableResponse.SerializeToString,
            ),
            'AcceptRide': grpc.unary_unary_rpc_method_handler(
                    servicer.AcceptRide,
                    request_deserializer=driver__pb2.AcceptRideRequest.FromString,
                    response_serializer=driver__pb2.AcceptRideResponse.SerializeToString,
            ),
            'RejectRide': grpc.unary_unary_rpc_method_handler(
                    servicer.RejectRide,
                    request_deserializer=driver__pb2.RejectRideRequest.FromString,
                    response_serializer=driver__pb2.RejectRideResponse.SerializeToString,
            ),
            'TimedOutRide': grpc.unary_unary_rpc_method_handler(
                    servicer.TimedOutRide,
                    request_deserializer=driver__pb2.TimedOutRideRequest.FromString,
                    response_serializer=driver__pb2.TimedOutRideResponse.SerializeToString,
            ),
            'CompleteRide': grpc.unary_unary_rpc_method_handler(
                    servicer.CompleteRide,
                    request_deserializer=driver__pb2.RideCompletionRequest.FromString,
                    response_serializer=driver__pb2.RideCompletionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'driver.Driver', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('driver.Driver', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Driver(object):
    """Drivers announce to a server (chosen acc to load balancing) that they are available
    for a ride, and wait for a response. If the server has an offer, the client waits
    till the timeout for the user to accept/reject and responds accordingly
    Once the ride is completed, it announces that to a server too.

    """

    @staticmethod
    def AmAvailable(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/driver.Driver/AmAvailable',
            driver__pb2.AmAvailableRequest.SerializeToString,
            driver__pb2.AmAvailableResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AcceptRide(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/driver.Driver/AcceptRide',
            driver__pb2.AcceptRideRequest.SerializeToString,
            driver__pb2.AcceptRideResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RejectRide(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/driver.Driver/RejectRide',
            driver__pb2.RejectRideRequest.SerializeToString,
            driver__pb2.RejectRideResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TimedOutRide(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/driver.Driver/TimedOutRide',
            driver__pb2.TimedOutRideRequest.SerializeToString,
            driver__pb2.TimedOutRideResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CompleteRide(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/driver.Driver/CompleteRide',
            driver__pb2.RideCompletionRequest.SerializeToString,
            driver__pb2.RideCompletionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
