# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: rider.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'rider.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0brider.proto\x12\x05rider\"M\n\x0bRideRequest\x12\x10\n\x08rider_id\x18\x01 \x01(\t\x12\x17\n\x0fpickup_location\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65stination\x18\x03 \x01(\t\"\x1f\n\x0cRideResponse\x12\x0f\n\x07ride_id\x18\x01 \x01(\t\"6\n\x11RideStatusRequest\x12\x10\n\x08rider_id\x18\x01 \x01(\t\x12\x0f\n\x07ride_id\x18\x02 \x01(\t\"4\n\x12RideStatusResponse\x12\x0e\n\x06\x64river\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\x05\x32\x85\x01\n\x05Rider\x12\x36\n\x0bRequestRide\x12\x12.rider.RideRequest\x1a\x13.rider.RideResponse\x12\x44\n\rGetRideStatus\x12\x18.rider.RideStatusRequest\x1a\x19.rider.RideStatusResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rider_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RIDEREQUEST']._serialized_start=22
  _globals['_RIDEREQUEST']._serialized_end=99
  _globals['_RIDERESPONSE']._serialized_start=101
  _globals['_RIDERESPONSE']._serialized_end=132
  _globals['_RIDESTATUSREQUEST']._serialized_start=134
  _globals['_RIDESTATUSREQUEST']._serialized_end=188
  _globals['_RIDESTATUSRESPONSE']._serialized_start=190
  _globals['_RIDESTATUSRESPONSE']._serialized_end=242
  _globals['_RIDER']._serialized_start=245
  _globals['_RIDER']._serialized_end=378
# @@protoc_insertion_point(module_scope)
