# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import document_pb2 as document__pb2

GRPC_GENERATED_VERSION = '1.66.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in document_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DocumentServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.InitializeDocument = channel.unary_unary(
                '/DocumentService/InitializeDocument',
                request_serializer=document__pb2.Change.SerializeToString,
                response_deserializer=document__pb2.Change.FromString,
                _registered_method=True)
        self.EditDocument = channel.unary_unary(
                '/DocumentService/EditDocument',
                request_serializer=document__pb2.Change.SerializeToString,
                response_deserializer=document__pb2.Ack.FromString,
                _registered_method=True)
        self.SyncDocument = channel.unary_stream(
                '/DocumentService/SyncDocument',
                request_serializer=document__pb2.SyncRequest.SerializeToString,
                response_deserializer=document__pb2.Change.FromString,
                _registered_method=True)


class DocumentServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def InitializeDocument(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EditDocument(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SyncDocument(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DocumentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'InitializeDocument': grpc.unary_unary_rpc_method_handler(
                    servicer.InitializeDocument,
                    request_deserializer=document__pb2.Change.FromString,
                    response_serializer=document__pb2.Change.SerializeToString,
            ),
            'EditDocument': grpc.unary_unary_rpc_method_handler(
                    servicer.EditDocument,
                    request_deserializer=document__pb2.Change.FromString,
                    response_serializer=document__pb2.Ack.SerializeToString,
            ),
            'SyncDocument': grpc.unary_stream_rpc_method_handler(
                    servicer.SyncDocument,
                    request_deserializer=document__pb2.SyncRequest.FromString,
                    response_serializer=document__pb2.Change.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'DocumentService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('DocumentService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DocumentService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def InitializeDocument(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/DocumentService/InitializeDocument',
            document__pb2.Change.SerializeToString,
            document__pb2.Change.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EditDocument(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/DocumentService/EditDocument',
            document__pb2.Change.SerializeToString,
            document__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SyncDocument(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/DocumentService/SyncDocument',
            document__pb2.SyncRequest.SerializeToString,
            document__pb2.Change.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class LoggerServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.LogDocumentChange = channel.stream_unary(
                '/LoggerService/LogDocumentChange',
                request_serializer=document__pb2.Change.SerializeToString,
                response_deserializer=document__pb2.Ack.FromString,
                _registered_method=True)


class LoggerServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def LogDocumentChange(self, request_iterator, context):
        """Server sends the document changes to the logger
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LoggerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'LogDocumentChange': grpc.stream_unary_rpc_method_handler(
                    servicer.LogDocumentChange,
                    request_deserializer=document__pb2.Change.FromString,
                    response_serializer=document__pb2.Ack.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'LoggerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('LoggerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LoggerService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def LogDocumentChange(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/LoggerService/LogDocumentChange',
            document__pb2.Change.SerializeToString,
            document__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
