# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: document.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'document.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x64ocument.proto\"5\n\x0bSyncRequest\x12\x11\n\tclient_id\x18\x01 \x01(\t\x12\x13\n\x0blast_change\x18\x02 \x01(\x03\"f\n\x06\x43hange\x12\x11\n\tclient_id\x18\x01 \x01(\t\x12\x11\n\toperation\x18\x02 \x01(\t\x12\x13\n\x0blast_change\x18\x03 \x01(\x03\x12\x0f\n\x07\x63ontent\x18\x04 \x01(\t\x12\x10\n\x08position\x18\x05 \x01(\x03\"\'\n\x03\x41\x63k\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\x81\x01\n\x0f\x44ocumentService\x12&\n\x12InitializeDocument\x12\x07.Change\x1a\x07.Change\x12\x1d\n\x0c\x45\x64itDocument\x12\x07.Change\x1a\x04.Ack\x12\'\n\x0cSyncDocument\x12\x0c.SyncRequest\x1a\x07.Change0\x01\x32\x35\n\rLoggerService\x12$\n\x11LogDocumentChange\x12\x07.Change\x1a\x04.Ack(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'document_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SYNCREQUEST']._serialized_start=18
  _globals['_SYNCREQUEST']._serialized_end=71
  _globals['_CHANGE']._serialized_start=73
  _globals['_CHANGE']._serialized_end=175
  _globals['_ACK']._serialized_start=177
  _globals['_ACK']._serialized_end=216
  _globals['_DOCUMENTSERVICE']._serialized_start=219
  _globals['_DOCUMENTSERVICE']._serialized_end=348
  _globals['_LOGGERSERVICE']._serialized_start=350
  _globals['_LOGGERSERVICE']._serialized_end=403
# @@protoc_insertion_point(module_scope)
